/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSupRouteImport } from './routes/_authenticated/sup'
import { Route as AuthenticatedMapRouteImport } from './routes/_authenticated/map'
import { Route as AuthenticatedKpiRouteImport } from './routes/_authenticated/kpi'
import { Route as AuthenticatedCopRouteImport } from './routes/_authenticated/cop'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSupRoute = AuthenticatedSupRouteImport.update({
  id: '/sup',
  path: '/sup',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMapRoute = AuthenticatedMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKpiRoute = AuthenticatedKpiRouteImport.update({
  id: '/kpi',
  path: '/kpi',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCopRoute = AuthenticatedCopRouteImport.update({
  id: '/cop',
  path: '/cop',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/cop': typeof AuthenticatedCopRoute
  '/kpi': typeof AuthenticatedKpiRoute
  '/map': typeof AuthenticatedMapRoute
  '/sup': typeof AuthenticatedSupRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/cop': typeof AuthenticatedCopRoute
  '/kpi': typeof AuthenticatedKpiRoute
  '/map': typeof AuthenticatedMapRoute
  '/sup': typeof AuthenticatedSupRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/cop': typeof AuthenticatedCopRoute
  '/_authenticated/kpi': typeof AuthenticatedKpiRoute
  '/_authenticated/map': typeof AuthenticatedMapRoute
  '/_authenticated/sup': typeof AuthenticatedSupRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/configuracoes'
    | '/cop'
    | '/kpi'
    | '/map'
    | '/sup'
  fileRoutesByTo: FileRoutesByTo
  to: '/auth' | '/configuracoes' | '/cop' | '/kpi' | '/map' | '/sup' | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/configuracoes'
    | '/_authenticated/cop'
    | '/_authenticated/kpi'
    | '/_authenticated/map'
    | '/_authenticated/sup'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sup': {
      id: '/_authenticated/sup'
      path: '/sup'
      fullPath: '/sup'
      preLoaderRoute: typeof AuthenticatedSupRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/map': {
      id: '/_authenticated/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof AuthenticatedMapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kpi': {
      id: '/_authenticated/kpi'
      path: '/kpi'
      fullPath: '/kpi'
      preLoaderRoute: typeof AuthenticatedKpiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cop': {
      id: '/_authenticated/cop'
      path: '/cop'
      fullPath: '/cop'
      preLoaderRoute: typeof AuthenticatedCopRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedCopRoute: typeof AuthenticatedCopRoute
  AuthenticatedKpiRoute: typeof AuthenticatedKpiRoute
  AuthenticatedMapRoute: typeof AuthenticatedMapRoute
  AuthenticatedSupRoute: typeof AuthenticatedSupRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedCopRoute: AuthenticatedCopRoute,
  AuthenticatedKpiRoute: AuthenticatedKpiRoute,
  AuthenticatedMapRoute: AuthenticatedMapRoute,
  AuthenticatedSupRoute: AuthenticatedSupRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
